In [84]:
#import statements

import pandas as pd
import matplotlib.pyplot as plt

In [85]:
#Declaring of link to dataset
url = "https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/AI%20and%20Digital%20Media/Global_AI_Content_Impact_Dataset.csv"
ai_df = pd.read_csv(url)
ai_df.info() #displaying basic information about the dataset

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     200 non-null    str
 1   Year                                        200 non-null    int64
 2   Industry                                    200 non-null    str
 3   AI Adoption Rate (%)                        200 non-null    float64
 4   AI-Generated Content Volume (TBs per year)  200 non-null    float64
 5   Job Loss Due to AI (%)                      200 non-null    float64
 6   Revenue Increase Due to AI (%)              200 non-null    float64
 7   Human-AI Collaboration Rate (%)             200 non-null    float64
 8   Top AI Tools Used                           200 non-null    str
 9   Regulation Status                           200 non-null    str
 10  Consumer Trust in AI (%)                    200 non-null    float64
 11  Market Share of AI Companies (%)            200 non-null    float64
dtypes: float64(7), int64(1), str(4)
memory usage: 18.9 KB

In [10]:
ai_df.head(5)

,Country,Year,Industry,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Top AI Tools Used,Regulation Status,Consumer Trust in AI (%),Market Share of AI Companies (%)
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41

In [ ]:
#Dictionary with the first valid year for each AI tool (release dates)
first_valid_year= {
    'Bard': 2023,
    'ChatGPT': 2022,
    'Claude': 2023,
    'DALL-E': 2021,
    'Midjourney': 2022,
    'Stable Diffusion': 2022,
    'Synthesia': 2020
}
#list for holding the indices of rows with mismatched years 
wrong_list = []
mismatch_count= 0 #counter for number of rows with mismatched years

#for loop to go through the rows
for i, row in ai_df.iterrows():
    tool = row['Top AI Tools Used']
    year = row['Year']
    
    #conditional: if df year is less tha the valid year for the tool,
    #it will add the row's index to the list
    if year < first_valid_year[tool]:
        mismatch_count += 1
        wrong_list.append(i)

        #If wrong, it will update the year value with the release date year
        correct_year = first_valid_year[tool]
        ai_df.loc[i, 'Year'] = correct_year

#prints the incorrect count, and the list of indices (only on the first and fresh run of this cell)
print('Mismatch Count:', mismatch_count)
print('Indices of Mismatched Rows:', wrong_list)
#returns the first 5 rows of the dataframe to verify the changes
ai_df.head()

Mismatch Count: 72
Indices of Mismatched Rows: [0, 3, 4, 5, 12, 13, 26, 27, 30, 39, 40, 46, 47, 49, 51, 54, 60, 61, 65, 67, 71, 72, 74, 77, 80, 88, 89, 91, 94, 99, 101, 102, 106, 111, 112, 114, 119, 121, 122, 124, 126, 128, 134, 135, 136, 137, 138, 140, 141, 142, 144, 147, 148, 154, 158, 161, 162, 163, 165, 169, 170, 176, 178, 179, 180, 181, 184, 186, 189, 191, 196, 199]

,Country,Year,Industry,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Top AI Tools Used,Regulation Status,Consumer Trust in AI (%),Market Share of AI Companies (%)
0,South Korea,2023,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2023,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2022,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41

In [87]:
ai_df.isna().sum() #Checking for missing or null values in the dataset

Country                                       0
Year                                          0
Industry                                      0
AI Adoption Rate (%)                          0
AI-Generated Content Volume (TBs per year)    0
Job Loss Due to AI (%)                        0
Revenue Increase Due to AI (%)                0
Human-AI Collaboration Rate (%)               0
Top AI Tools Used                             0
Regulation Status                             0
Consumer Trust in AI (%)                      0
Market Share of AI Companies (%)              0
dtype: int64

In [88]:
ai_df.duplicated().sum() #Checking for duplicates in the dataset
ai_df.shape

(200, 12)

In [ ]:
# GRAPH - still a work in progress, Ironing out my plan...
# #Goal, make a multiple in one line graph for each country
#ob loss due to AI over time

# filtered_data = ai_df[ai_df["Country"] == "China"]

# filtered_data
# plt.plot(filtered_data["Year"], filtered_data["Job Loss Due to AI (%)"])


# plt.title("Years vs Job Loss Due to AI")
# plt.xlabel("Years")
# plt.ylabel("Job Loss Due to AI (%)")

# plt.show()